### ISSUE TITLE
Tidb docker compose file

### ISSUE THREAD

**Issue by siddhantprateek** [Anindyadeep/hnm-search#3]
```yaml
version: '3'

services:
  pd0:
    image: pingcap/pd:nightly
    ports:
      - "2379"
    volumes:
      - ./tidb/config/pd-nightly-tiflash.toml:/pd.toml:ro
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd
      - --config=/pd.toml
      - --log-file=/logs/pd.log
    restart: on-failure
  tikv:
    image: pingcap/tikv:nightly
    volumes:
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --status-addr=tikv:20180
      - --data-dir=/data/tikv
      - --pd=pd0:2379
      - --log-file=/logs/tikv.log
    depends_on:
      - "pd0"
    restart: on-failure
  tidb:
    image: pingcap/tidb:nightly
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./tidb/logs:/logs
    command:
      - --status=10080
      - --advertise-address=tidb
      - --store=tikv
      - --path=pd0:2379
      - --log-file=/logs/tidb.log
    depends_on:
      - "tikv"
    restart: on-failure
  tiflash:
   image: pingcap/tiflash:nightly
   volumes:
     - ./tidb/config/tiflash-nightly.toml:/tiflash.toml:ro
     - ./tidb/config/tiflash-learner-nightly.toml:/tiflash-learner.toml:ro
     - ./tidb/data:/data
     - ./tidb/logs:/logs
   command:
     - --config=/tiflash.toml
   depends_on:
     - "tikv"
     - "tidb"
   restart: on-failure

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=tidb
      - PMA_PORT=4000
      - PMA_USER=root
      # - MYSQL_USERNAME=root
    ports:
      - 24581:80
```

Forward Request 

```bash
ngrok tcp 4000
```

mysql connection
```
mysql -h tcp://<host> -P <port>  -u root
```

**Comment by siddhantprateek** [comment]
@Anindyadeep use it from here

**Comment by siddhantprateek** [comment]
https://docs.pingcap.com/tidb/stable/dev-guide-sample-application-python-pymysql

**Comment by siddhantprateek** [comment]
@Anindyadeep update in docker compose

`initdb.sh`
```
#!/bin/bash
set -e

until mysql -h 127.0.0.1 -P 4000 -u root -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1"; do
  echo "Waiting for TiDB to be ready..."
  sleep 1
done

mysql -h 127.0.0.1 -P 4000 -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    ALTER USER 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
    FLUSH PRIVILEGES;
EOSQL

echo "TiDB initialized successfully!"
```

provide required permissions `chmod +x initdb.sh`

updated compose file
```yaml
version: '3'

services:
  pd0:
    image: pingcap/pd:nightly
    ports:
      - "2379"
    volumes:
      - ./tidb/config/pd-nightly-tiflash.toml:/pd.toml:ro
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd
      - --config=/pd.toml
      - --log-file=/logs/pd.log
    restart: on-failure
  tikv:
    image: pingcap/tikv:nightly
    volumes:
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --status-addr=tikv:20180
      - --data-dir=/data/tikv
      - --pd=pd0:2379
      - --log-file=/logs/tikv.log
    depends_on:
      - "pd0"
    restart: on-failure
  tidb:
    image: pingcap/tidb:nightly
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./tidb/logs:/logs
      - ./init-script.sh:/docker-entrypoint-initdb.d/init-script.sh
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpass
    command:
      - --status=10080
      - --advertise-address=tidb
      - --store=tikv
      - --path=pd0:2379
      - --log-file=/logs/tidb.log
    depends_on:
      - "tikv"
    restart: on-failure
  tiflash:
   image: pingcap/tiflash:nightly
   volumes:
     - ./tidb/config/tiflash-nightly.toml:/tiflash.toml:ro
     - ./tidb/config/tiflash-learner-nightly.toml:/tiflash-learner.toml:ro
     - ./tidb/data:/data
     - ./tidb/logs:/logs
   command:
     - --config=/tiflash.toml
   depends_on:
     - "tikv"
     - "tidb"
   restart: on-failure

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=tidb
      - PMA_PORT=4000
      - PMA_USER=root
      # - MYSQL_USERNAME=root
    ports:
      - 24581:80
```
